version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMINS=${ADMINS}
      - SQLITE_PATH=/app/data/bot.db
    volumes:
      - bot_data:/app/data
    dns:
      - 1.1.1.1
      - 8.8.8.8

volumes:
  bot_data: